import edgedb.schema.std

class local_date(edgedb.schema.std.AnyScalar):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class local_datetime(edgedb.schema.std.AnyScalar):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class local_time(edgedb.schema.std.AnyScalar):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
