import dataclasses
from typing import Any
import edgedb.schema

@dataclasses.dataclass
class AbstractConfig(ConfigObject):
    allow_dml_in_functions: bool = ...
    default_statistics_target: str = ...
    effective_cache_size: str = ...
    effective_io_concurrency: str = ...
    listen_addresses: str = ...
    listen_port: int = ...
    query_work_mem: str = ...
    shared_buffers: str = ...

@dataclasses.dataclass
class Auth(ConfigObject):
    comment: str = ...
    priority: int = ...
    user: str = ...

@dataclasses.dataclass
class AuthMethod(ConfigObject): ...

@dataclasses.dataclass
class Config(AbstractConfig): ...

@dataclasses.dataclass
class ConfigObject(edgedb.schema.BaseObject):
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...

@dataclasses.dataclass
class DatabaseConfig(AbstractConfig): ...

@dataclasses.dataclass
class SCRAM(AuthMethod): ...

@dataclasses.dataclass
class SystemConfig(AbstractConfig): ...

@dataclasses.dataclass
class Trust(AuthMethod): ...
