from typing import Any
import edgedb.schema

class AbstractConfig(ConfigObject):
    allow_dml_in_functions: bool = ...
    default_statistics_target: str = ...
    effective_cache_size: str = ...
    effective_io_concurrency: str = ...
    listen_addresses: str = ...
    listen_port: int = ...
    query_work_mem: str = ...
    shared_buffers: str = ...

class Auth(ConfigObject):
    comment: str = ...
    priority: int = ...
    user: str = ...

class AuthMethod(ConfigObject): ...

class Config(AbstractConfig): ...

class ConfigObject(edgedb.schema.BaseObject):
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...

class DatabaseConfig(AbstractConfig): ...

class SCRAM(AuthMethod): ...

class SystemConfig(AbstractConfig): ...

class Trust(AuthMethod): ...
