import dataclasses
from typing import Any
import edgedb.schema
import edgedb.schema.std

@dataclasses.dataclass
class Alias(AnnotationSubject):
    expr: str = ...

@dataclasses.dataclass
class Annotation(InheritingObject):
    inheritable: bool = ...

@dataclasses.dataclass
class AnnotationSubject(Object): ...

@dataclasses.dataclass
class Array(CollectionType): ...

@dataclasses.dataclass
class CallableObject(AnnotationSubject):
    return_typemod: TypeModifier = ...

class Cardinality(edgedb.schema.std.anyenum): ...

@dataclasses.dataclass
class Cast(AnnotationSubject, VolatilitySubject):
    allow_assignment: bool = ...
    allow_implicit: bool = ...

@dataclasses.dataclass
class CollectionType(Type): ...

@dataclasses.dataclass
class ConsistencySubject(InheritingObject): ...

@dataclasses.dataclass
class Constraint(InheritingObject, CallableObject):
    delegated: bool = ...
    errmessage: str = ...
    expr: str = ...
    finalexpr: str = ...
    subjectexpr: str = ...

@dataclasses.dataclass
class Delta(Object): ...

@dataclasses.dataclass
class Extension(AnnotationSubject): ...

@dataclasses.dataclass
class Function(CallableObject, VolatilitySubject): ...

@dataclasses.dataclass
class Index(AnnotationSubject):
    expr: str = ...

@dataclasses.dataclass
class InheritingObject(SubclassableObject): ...

@dataclasses.dataclass
class Link(Source, Pointer):
    on_target_delete: TargetDeleteAction = ...

@dataclasses.dataclass
class Migration(AnnotationSubject):
    message: str = ...
    script: str = ...

@dataclasses.dataclass
class Module(AnnotationSubject): ...

@dataclasses.dataclass
class Object(edgedb.schema.BaseObject):
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    builtin: bool = ...
    internal: bool = ...
    name: str = ...

@dataclasses.dataclass
class ObjectType(Type, ConsistencySubject, Source):
    compound_type: bool = ...
    is_compound_type: bool = ...

@dataclasses.dataclass
class Operator(CallableObject, VolatilitySubject):
    abstract: bool = ...
    is_abstract: bool = ...
    operator_kind: OperatorKind = ...

class OperatorKind(edgedb.schema.std.anyenum): ...

@dataclasses.dataclass
class Parameter(Object):
    default: str = ...
    kind: ParameterKind = ...
    num: int = ...
    typemod: TypeModifier = ...

class ParameterKind(edgedb.schema.std.anyenum): ...

@dataclasses.dataclass
class Pointer(AnnotationSubject, ConsistencySubject):
    cardinality: Cardinality = ...
    default: str = ...
    expr: str = ...
    readonly: bool = ...
    required: bool = ...

@dataclasses.dataclass
class Property(Pointer): ...

@dataclasses.dataclass
class PseudoType(Type, InheritingObject): ...

@dataclasses.dataclass
class ScalarType(Type, ConsistencySubject):
    default: str = ...

@dataclasses.dataclass
class Source(Object): ...

@dataclasses.dataclass
class SubclassableObject(Object):
    abstract: bool = ...
    final: bool = ...
    is_abstract: bool = ...
    is_final: bool = ...

class TargetDeleteAction(edgedb.schema.std.anyenum): ...

@dataclasses.dataclass
class Tuple(CollectionType): ...

@dataclasses.dataclass
class TupleElement(edgedb.schema.Object):
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    name: str = ...

@dataclasses.dataclass
class Type(SubclassableObject, AnnotationSubject):
    expr: str = ...
    from_alias: bool = ...
    is_from_alias: bool = ...

class TypeModifier(edgedb.schema.std.anyenum): ...

class Volatility(edgedb.schema.std.anyenum): ...

@dataclasses.dataclass
class VolatilitySubject(Object):
    volatility: Volatility = ...
