from typing import Tuple

import edgedb.schema.std

class Alias(AnnotationSubject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    expr: str = ...

class Annotation(InheritingObject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    inheritable: bool = ...

class AnnotationSubject(Object):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...

class Array(CollectionType):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...

class CallableObject(AnnotationSubject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    return_typemod: TypeModifier = ...

class Cardinality(edgedb.schema.std.anyenum):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class Cast(AnnotationSubject, VolatilitySubject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    allow_assignment: bool = ...
    allow_implicit: bool = ...

class CollectionType(Type):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...

class ConsistencySubject(InheritingObject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...

class Constraint(InheritingObject, CallableObject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    delegated: bool = ...
    errmessage: str = ...
    expr: str = ...
    finalexpr: str = ...
    subjectexpr: str = ...

class Delta(Object):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...

class Extension(AnnotationSubject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...

class Function(CallableObject, VolatilitySubject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...

class Index(AnnotationSubject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    expr: str = ...

class InheritingObject(SubclassableObject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...

class Link(Source, Pointer):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    on_target_delete: TargetDeleteAction = ...

class Migration(AnnotationSubject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    message: str = ...
    script: str = ...

class Module(AnnotationSubject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...

class Object(edgedb.schema.std.BaseObject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    builtin: bool = ...
    internal: bool = ...
    name: str = ...

class ObjectType(Type, ConsistencySubject, Source):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    compound_type: bool = ...
    is_compound_type: bool = ...

class Operator(CallableObject, VolatilitySubject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    abstract: bool = ...
    is_abstract: bool = ...
    operator_kind: OperatorKind = ...

class OperatorKind(edgedb.schema.std.anyenum):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class Parameter(Object):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    default: str = ...
    kind: ParameterKind = ...
    num: int = ...
    typemod: TypeModifier = ...

class ParameterKind(edgedb.schema.std.anyenum):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class Pointer(AnnotationSubject, ConsistencySubject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    cardinality: Cardinality = ...
    default: str = ...
    expr: str = ...
    readonly: bool = ...
    required: bool = ...

class Property(Pointer):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...

class PseudoType(Type, InheritingObject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...

class ScalarType(Type, ConsistencySubject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    default: str = ...

class Source(Object):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...

class SubclassableObject(Object):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    abstract: bool = ...
    final: bool = ...
    is_abstract: bool = ...
    is_final: bool = ...

class TargetDeleteAction(edgedb.schema.std.anyenum):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class Tuple(CollectionType):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...

class TupleElement(edgedb.schema.std.Object):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    name: str = ...

class Type(SubclassableObject, AnnotationSubject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    expr: str = ...
    from_alias: bool = ...
    is_from_alias: bool = ...

class TypeModifier(edgedb.schema.std.anyenum):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class Volatility(edgedb.schema.std.anyenum):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class VolatilitySubject(Object):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    volatility: Volatility = ...
