import dataclasses
from typing import Any
import edgedb.schema

class anyenum(edgedb.schema.anyscalar): ...

class anyfloat(anyreal): ...

class anyint(anyreal): ...

class anynumeric(anyreal): ...

class anyreal(edgedb.schema.anyscalar): ...

class bigint(anyint, anynumeric): ...

class bool(edgedb.schema.anyscalar): ...

class bytes(edgedb.schema.anyscalar): ...

class datetime(edgedb.schema.anyscalar): ...

class decimal(anynumeric): ...

class duration(edgedb.schema.anyscalar): ...

class float32(anyfloat): ...

class float64(anyfloat): ...

class int16(anyint): ...

class int32(anyint): ...

class int64(anyint): ...

class json(edgedb.schema.anyscalar): ...

class sequence(int64): ...

class str(edgedb.schema.anyscalar): ...

class uuid(edgedb.schema.anyscalar): ...
