class BaseObject:
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    def __init__(self, *args, **kwargs) -> None: ...

class Object(BaseObject):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class anyenum(AnyScalar):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class anyfloat(anyreal):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class anyint(anyreal):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class anynumeric(anyreal):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class anyreal(AnyScalar):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class anyscalar:
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class bigint(anyint, anynumeric):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class bool(AnyScalar):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class bytes(AnyScalar):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class datetime(AnyScalar):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class decimal(anynumeric):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class duration(AnyScalar):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class float32(anyfloat):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class float64(anyfloat):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class int16(anyint):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class int32(anyint):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class int64(anyint):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class json(AnyScalar):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class sequence(int64):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class str(AnyScalar):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...

class uuid(AnyScalar):
    __annotations__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
