import dataclasses
from typing import Any
import edgedb.schema

@dataclasses.dataclass
class Mutation(edgedb.schema.BaseObject):
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __typename: str = ...

@dataclasses.dataclass
class Query(edgedb.schema.BaseObject):
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __typename: str = ...
