from typing import Any
import edgedb.schema

class Mutation(edgedb.schema.BaseObject):
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __typename: str = ...

class Query(edgedb.schema.BaseObject):
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __typename: str = ...
