import edgedb.schema.std

class Mutation(edgedb.schema.std.BaseObject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    __typename: str = ...

class Query(edgedb.schema.std.BaseObject):
    __init__: Any = ...
    __annotations__: Any = ...
    __dataclass_fields__: Any = ...
    __dataclass_params__: Any = ...
    __edb_abstract__: Any = ...
    __edb_bases__: Any = ...
    __edb_name__: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    __typename: str = ...
