from typing import Any
import edgedb.schema.schema
import edgedb.schema.std

class Database(SystemObject):
    name: str = ...

class ExtensionPackage(SystemObject):
    script: str = ...

class Role(edgedb.schema.schema.InheritingObject, SystemObject):
    is_superuser: bool = ...
    name: str = ...
    password: str = ...
    superuser: bool = ...

class SystemObject(edgedb.schema.schema.AnnotationSubject): ...

class TransactionIsolation(edgedb.schema.std.anyenum): ...

class VersionStage(edgedb.schema.std.anyenum): ...
